// frontend/frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="min-vh-100 d-flex align-items-center justify-content-center bg-light">
      <div class="card shadow" style="width: 400px;">
        <div class="card-body p-5">
          <div class="text-center mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi text-primary mb-3">
              <path d="M12 1a3 3 0 00-3 3v8a3 3 0 006 0V4a3 3 0 00-3-3z"/>
              <path d="M19 10H5a2 2 0 00-2 2v1a2 2 0 002 2h14a2 2 0 002-2v-1a2 2 0 00-2-2z"/>
              <circle cx="12" cy="14" r="4"/>
            </svg>
            <h3>Panel Admin</h3>
            <p class="text-muted">Ingresa tus credenciales</p>
          </div>

          <div *ngIf="error" class="alert alert-danger">
            {{ error }}
          </div>

          <form (ngSubmit)="login()">
            <div class="mb-3">
              <label class="form-label">Usuario</label>
              <input type="text" class="form-control" [(ngModel)]="usuario" name="usuario" required>
            </div>

            <div class="mb-3">
              <label class="form-label">Contraseña</label>
              <input type="password" class="form-control" [(ngModel)]="password" name="password" required>
            </div>

            <div class="mb-3 text-center">
              <div class="bg-light p-3 rounded">
                <small class="text-muted">reCAPTCHA (demo)</small>
              </div>
            </div>

            <button type="submit" class="btn btn-primary w-100" [disabled]="loading">
              {{ loading ? 'Ingresando...' : 'Ingresar' }}
            </button>
          </form>

          <div class="text-center mt-3">
            <a routerLink="/" class="text-decoration-none">← Volver al inicio</a>
          </div>
        </div>
      </div>
    </div>
  `
})
export class LoginComponent {
  usuario = '';
  password = '';
  loading = false;
  error = '';

  constructor(
    private api: ApiService,
    private auth: AuthService,
    private router: Router
  ) {}

  login(): void {
    this.loading = true;
    this.error = '';

    this.api.login(this.usuario, this.password, 'demo-token').subscribe({
      next: (data) => {
        this.auth.login(data.token, data.usuario);
        this.router.navigate(['/admin']);
      },
      error: (err) => {
        this.error = err.error?.error || 'Credenciales inválidas';
      },
      complete: () => this.loading = false
    });
  }
}

// frontend/frontend/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { authService } from '../services/api';
import { Lock, AlertCircle } from 'lucide-react';

const RECAPTCHA_SITE_KEY = import.meta.env.VITE_RECAPTCHA_SITE_KEY || 'tu_clave_publica_recaptcha';

function Login() {
  const [formData, setFormData] = useState({ usuario: '', password: '' });
  const [recaptchaToken, setRecaptchaToken] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const recaptchaResponse = await window.grecaptcha?.execute(RECAPTCHA_SITE_KEY, { action: 'login' });
      const token = recaptchaResponse || 'demo-token';

      const response = await authService.login({
        ...formData,
        recaptchaToken: token
      });

      login(response.data.token, response.data.usuario);
      navigate('/admin');
    } catch (err) {
      setError(err.response?.data?.error || 'Credenciales inválidas');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-primary-100 flex items-center justify-center">
      <div className="card w-full max-w-md">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-primary-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <Lock className="w-8 h-8 text-primary-600" />
          </div>
          <h1 className="text-2xl font-bold text-gray-800">Panel de Administración</h1>
          <p className="text-gray-600 mt-2">Ingresa tus credenciales</p>
        </div>

        {error && (
          <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-lg mb-6 flex items-center gap-2">
            <AlertCircle className="w-5 h-5" />
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Usuario</label>
            <input
              type="text"
              value={formData.usuario}
              onChange={(e) => setFormData({ ...formData, usuario: e.target.value })}
              className="input-field"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Contraseña</label>
            <input
              type="password"
              value={formData.password}
              onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              className="input-field"
              required
            />
          </div>

          <div id="recaptcha-container" className="flex justify-center"></div>

          <button
            type="submit"
            disabled={loading}
            className="btn-primary w-full py-3"
          >
            {loading ? 'Iniciando sesión...' : 'Ingresar'}
          </button>
        </form>

        <div className="mt-6 text-center">
          <a href="/" className="text-primary-600 hover:text-primary-800 text-sm">
            ← Volver al inicio
          </a>
        </div>
      </div>
    </div>
  );
}

export default Login;
